name: A Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running Workflow A"

      - name: Upload Test Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: teams-channel-notification-testing
          path: |
            README.md

      - name: Send to Microsoft Teams
        run: |
          ARTIFACT_URL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
      
          curl -H "Content-Type: application/json" \
               -d '{
                    "text": "✅ Build Completed\nDownload Artifact: '"$ARTIFACT_URL"'"
                   }' \
               ${{ vars.TEAMS_WEBHOOK_URL }}
