name: Main Workflow 2

on:
  workflow_dispatch:
permissions:
  contents: read
  actions: write
  
env:
  GH_TOKEN: ${{ github.token }}
  
jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      commonChanged: ${{ steps.set.outputs.commonChanged }}
    steps:
      - name: Fake detection for testing
        id: set
        run: |
          echo "commonChanged=false" >> $GITHUB_OUTPUT

  trigger-common:
    needs: detect-changes
    if: needs.detect-changes.outputs.commonChanged == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Common Workflow
        run: |
          gh workflow run common.yml --ref main --repo ${{ github.repository }}

  trigger-A:
    if: |
      always()
    needs: [detect-changes, trigger-common]
    runs-on: ubuntu-latest
    steps:
      - name: Trigger A Workflow
        run: |
          gh workflow run A.yml \
            --ref ${{ github.base_ref}} \
            --repo ${{ github.repository }}

  trigger-B:  
    if: |
      always()
    needs: [detect-changes, trigger-common]
    runs-on: ubuntu-latest
    steps:
      - name: Trigger B Workflow
        run: |
          gh workflow run B.yml \
            --ref ${{ github.base_ref}} \
            --repo ${{ github.repository }}

  trigger-C:
    if: |
      always()
    needs: [detect-changes, trigger-common]
    runs-on: ubuntu-latest
    steps:
      - name: Trigger C Workflow
        run: |
          gh workflow run C.yml --ref main --repo ${{ github.repository }}
